//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb1Ricardo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosPistas
    {
        public int CodigoUsuario { get; set; }
        public int CodigoPista { get; set; }
        public string EstadoPista { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Pistas Pistas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
